version: '3'

services:
  app_fintech:
    image: fintech_image
    container_name: fintech_container
    build: fintech
    mem_limit: 512m
    ports:
      - "9698:9698"
    env_file:
      - fintech/.env.docker 
    restart: always
            
    depends_on:
      my_fintech:
          condition: service_healthy
  my_fintech:
    image: postgres
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: root1
      POSTGRES_DATABASE: fintech_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10